# Site settings
title: DONGZAI.NET
description: >
  동짜이넷

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hitchhiker.ma" # the base hostname & protocol for your site

author:
  fullname: DONGJAE LEE
  googleplus: https://www.google.com/+dongjaeleek
  github: lidongzai
  twitter: dongzainet
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown
